/**
 * Comprehensive Nigerian LGA (Local Government Area) Data
 * Contains all 36 states + FCT with their respective LGAs
 * Last Updated: January 9, 2026
 */

export interface StateData {
  name: string;
  lgaCount: number;
  lgas: string[];
}

export const nigerianLGAData: Record<string, StateData> = {
  'Abia': {
    name: 'Abia',
    lgaCount: 17,
    lgas: [
      'Aba North',
      'Aba South',
      'Arochukwu',
      'Bende',
      'Ikwuano',
      'Isiala Ngwa North',
      'Isiala Ngwa South',
      'Isuikwuato',
      'Obi Ngwa',
      'Ohafia',
      'Osisioma Ngwa',
      'Ugwunagbo',
      'Ukwa East',
      'Ukwa West',
      'Umuahia North',
      'Umuahia South',
      'Umuneochi',
    ],
  },
  'Adamawa': {
    name: 'Adamawa',
    lgaCount: 21,
    lgas: [
      'Demsa',
      'Donga',
      'Fufure',
      'Ganye',
      'Girei',
      'Gombi',
      'Guyuk',
      'Hong',
      'Jada',
      'Jaimako',
      'Larmorde',
      'Madagali',
      'Maiha',
      'Mayo-Belwa',
      'Michika',
      'Mubi North',
      'Mubi South',
      'Numan',
      'Shelleng',
      'Song',
      'Yola North',
      'Yola South',
    ],
  },
  'Akwa Ibom': {
    name: 'Akwa Ibom',
    lgaCount: 31,
    lgas: [
      'Abak',
      'Eastern Obolo',
      'Eket',
      'Esit Eket',
      'Essien Udim',
      'Etim Ekpo',
      'Etinan',
      'Ibeno',
      'Ibesikpo Asutan',
      'Ibias',
      'Ibibio',
      'Ikot Abasi',
      'Ikot Ekpene',
      'Ini',
      'Iquita/Ibiono',
      'Isangele',
      'Itu',
      'Mbo',
      'Mkpat Enin',
      'Nsit Atai',
      'Nsit Ibom',
      'Nsit Ubium',
      'Obot Akara',
      'Okobo',
      'Onna',
      'Oron',
      'Oruk Anam',
      'Ukanafun',
      'Udung Uko',
      'Urue-Offong/Oruko',
      'Uyo',
    ],
  },
  'Anambra': {
    name: 'Anambra',
    lgaCount: 21,
    lgas: [
      'Aguata',
      'Anambra East',
      'Anambra West',
      'Anaocha',
      'Awka North',
      'Awka South',
      'Ayamelum',
      'Dunukofia',
      'Ekwusigo',
      'Enugu North',
      'Enugu South',
      'Idemili North',
      'Idemili South',
      'Ihiala',
      'Njikoka',
      'Nnewi North',
      'Nnewi South',
      'Ogbaru',
      'Okabia',
      'Onitsha North',
      'Onitsha South',
    ],
  },
  'Bauchi': {
    name: 'Bauchi',
    lgaCount: 20,
    lgas: [
      'Alkaleri',
      'Bauchi',
      'Bogoro',
      'Damboa',
      'Darazo',
      'Das',
      'Ganjuwa',
      'Giade',
      'Itas/Gadau',
      'Jada',
      'Kaita',
      'Kirfi',
      'Lere',
      'Misau',
      'Ningi',
      'Shira',
      'Tafawa Balewa',
      'Toro',
      'Warji',
      'Zaki',
    ],
  },
  'Bayelsa': {
    name: 'Bayelsa',
    lgaCount: 8,
    lgas: [
      'Brass',
      'Ekeremor',
      'Kolokuma/Opokuma',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Yenagoa',
    ],
  },
  'Benue': {
    name: 'Benue',
    lgaCount: 23,
    lgas: [
      'Ado',
      'Agatu',
      'Apa',
      'Buruku',
      'Gboko',
      'Guma',
      'Gwer East',
      'Gwer West',
      'Katsina-Ala',
      'Konshisha',
      'Makurdi',
      'Obi',
      'Ogbadibo',
      'Okpokwu',
      'Otukpo',
      'Tarka',
      'Ukum',
      'Ushongo',
      'Vandeikya',
    ],
  },
  'Borno': {
    name: 'Borno',
    lgaCount: 27,
    lgas: [
      'Abadam',
      'Askira/Uba',
      'Bama',
      'Bayo',
      'Biu',
      'Chibok',
      'Damboa',
      'Dikwa',
      'Geidam',
      'Gujba',
      'Guzamala',
      'Gwoza',
      'Hawul',
      'Jere',
      'Jigawa',
      'Kaba',
      'Kaga',
      'Kaita',
      'Konduga',
      'Kusar',
      'Kwan',
      'Mafa',
      'Magumeri',
      'Maiduguri',
      'Marte',
      'Mobbar',
      'Monguno',
      'Nganzai',
      'Nguru',
      'Shani',
    ],
  },
  'Cross River': {
    name: 'Cross River',
    lgaCount: 18,
    lgas: [
      'Akamkpa',
      'Akpabuyo',
      'Bakassi',
      'Bekwarra',
      'Biase',
      'Boki',
      'Calabar Municipal',
      'Calabar South',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obarakwo',
      'Odukpani',
      'Ogoja',
      'Obudu',
      'Ofemili',
      'Okurubong',
      'Yala',
    ],
  },
  'Delta': {
    name: 'Delta',
    lgaCount: 25,
    lgas: [
      'Aniocha North',
      'Aniocha South',
      'Bomadi',
      'Burutu',
      'Coperbelt',
      'Ethiope East',
      'Ethiope West',
      'Ika North East',
      'Ika South',
      'Isoko North',
      'Isoko South',
      'Ivie',
      'Ndokwa East',
      'Ndokwa West',
      'Nnewi East',
      'Nnewi West',
      'Ofagbe',
      'Okada',
      'Okpe',
      'Oleh',
      'Oshimili North',
      'Oshimili South',
      'Patani',
      'Sapele',
      'Udu',
      'Ughelli North',
      'Ughelli South',
      'Ukwuani',
      'Uvwie',
      'Warri North',
      'Warri South',
      'Warri South West',
    ],
  },
  'Ebonyi': {
    name: 'Ebonyi',
    lgaCount: 13,
    lgas: [
      'Abakaliki',
      'Afikpo North',
      'Afikpo South',
      'Ebonyi',
      'Ezza North',
      'Ezza South',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Izzi',
      'Ohaozara',
      'Ohaukwu',
      'Onicha',
    ],
  },
  'Edo': {
    name: 'Edo',
    lgaCount: 18,
    lgas: [
      'Akoko-Edo',
      'Egor',
      'Esan Central',
      'Esan North-East',
      'Esan South-East',
      'Esan West',
      'Etsako Central',
      'Etsako East',
      'Etsako West',
      'Igueben',
      'Ikpoba-Okha',
      'Oredo',
      'Orhionmwon',
      'Ovia North-East',
      'Ovia South-West',
      'Owan East',
      'Owan West',
      'Uhunmwonde',
    ],
  },
  'Ekiti': {
    name: 'Ekiti',
    lgaCount: 16,
    lgas: [
      'Ado-Ekiti',
      'Efon',
      'Ekiti East',
      'Ekiti South-West',
      'Ekiti West',
      'Emure',
      'Gbonyin',
      'Ido-Osi',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilejemeje',
      'Irepodun',
      'Ise/Orun',
      'Moba',
      'Oye',
    ],
  },
  'Enugu': {
    name: 'Enugu',
    lgaCount: 17,
    lgas: [
      'Aninri',
      'Awgu',
      'Enugu East',
      'Enugu North',
      'Enugu South',
      'Ezeagu',
      'Igbo-Etiti',
      'Igbo-Eze North',
      'Igbo-Eze South',
      'Isi-Uzo',
      'Nkanu East',
      'Nkanu West',
      'Nsukka',
      'Oji River',
      'Udenu',
      'Udi',
      'Uzo-Uwani',
    ],
  },
  'FCT': {
    name: 'Federal Capital Territory',
    lgaCount: 6,
    lgas: [
      'Abuja Municipal Area Council',
      'Bwari',
      'Gwagwalada',
      'Kuje',
      'Kwali',
      'Municipal Area Council',
    ],
  },
  'Gombe': {
    name: 'Gombe',
    lgaCount: 11,
    lgas: [
      'Akko',
      'Balanga',
      'Billiri',
      'Dukku',
      'Funakaye',
      'Gombe',
      'Kaltungo',
      'Kwami',
      'Nafada',
      'Shongom',
      'Yamaltu/Deba',
    ],
  },
  'Imo': {
    name: 'Imo',
    lgaCount: 27,
    lgas: [
      'Aboh-Mbaise',
      'Ahiazu-Mbaise',
      'Ehime-Mbano',
      'Eziinihitte-Mbaise',
      'Ezinihitte',
      'Ideato North',
      'Ideato South',
      'Idemili North',
      'Idemili South',
      'Iguhu',
      'Ihitte/Uboma',
      'Ikeduru',
      'Isiala Mbano',
      'Isimangano',
      'Isu',
      'Koloinu',
      'Losimegbe',
      'Ngor-Okpala',
      'Njaba',
      'Nwangele',
      'Nwangele',
      'Obowo',
      'Ohaozara',
      'Okigwe',
      'Onuimo',
      'Orlu',
      'Orogu',
      'Owerri Municipal',
      'Owerri North',
      'Owerri West',
      'Unuimo',
    ],
  },
  'Jigawa': {
    name: 'Jigawa',
    lgaCount: 27,
    lgas: [
      'Auyo',
      'Babbar',
      'Birin-Kudu',
      'Birnin-Kudu',
      'Dutse',
      'Gagarawa',
      'Garki',
      'Garum-Ballaji',
      'Gaya',
      'Guri',
      'Gumel',
      'Gundam',
      'Gwaram',
      'Hadejia',
      'Jahun',
      'Kafinhausa',
      'Kaugama',
      'Kazaure',
      'Kiri-Kasama',
      'Kiyawa',
      'Maigatari',
      'Malam-Madori',
      'Miga',
      'Ringim',
      'Sule-Tankarkar',
      'Taura',
      'Yankwashi',
    ],
  },
  'Kaduna': {
    name: 'Kaduna',
    lgaCount: 23,
    lgas: [
      'Birnin-Gwari',
      'Bombasa',
      'Chikun',
      'Giwa',
      'Igabi',
      'Ikara',
      'Jaba',
      'Jadi',
      'Kachia',
      'Kaduna North',
      'Kaduna South',
      'Kagarko',
      'Kajuru',
      'Kateri',
      'Kaura',
      'Kauru',
      'Kudan',
      'Lere',
      'Makarfi',
      'Sabon-Gari',
      'Saminaka',
      'Sanga',
      'Zagon-Kataf',
    ],
  },
  'Kano': {
    name: 'Kano',
    lgaCount: 44,
    lgas: [
      'Ajinkyire',
      'Albasu',
      'Bagwaji',
      'Bebeji',
      'Bichi',
      'Bunkure',
      'Dala',
      'Dambatta',
      'Dawakin Kudu',
      'Dawakin Tofa',
      'Doguwa',
      'Fagge',
      'Gabasawa',
      'Garko',
      'Garun Mallam',
      'Gaya',
      'Gezawa',
      'Gwale',
      'Gwarzo',
      'Kabo',
      'Kachumbari',
      'Kahuta',
      'Kaikaji',
      'Kaki',
      'Kankara',
      'Kankaromu',
      'Kano Municipal',
      'Karaye',
      'Karfi',
      'Kaura Namoda',
      'Kegudu',
      'Kibiya',
      'Kiri Kasama',
      'Kofar',
      'Kofa',
      'Kumia',
      'Kura',
      'Kurkur',
      'Kursua',
      'Kwankwasoro',
      'Kware',
      'Madobi',
      'Makoda',
      'Minjibir',
      'Munye',
      'Murmur',
      'Musawa',
      'Mutumbi',
      'Nafada',
      'Nasarawa',
      'Rano',
      'Rinjin',
      'Rogo',
      'Rons',
      'Saidutsinma',
      'Shanono',
      'Sumaila',
      'Sumbul',
      'Takai',
      'Tarauni',
      'Tofa',
      'Tsanyawa',
      'Tudun Wada',
      'Ungogo',
      'Wailari',
      'Waje',
      'Wudil',
    ],
  },
  'Katsina': {
    name: 'Katsina',
    lgaCount: 34,
    lgas: [
      'Achalonu',
      'Ajiwa',
      'Akiafu',
      'Ala',
      'Araga',
      'Arokoyo',
      'Asaa',
      'Atu',
      'Auchi',
      'Auwagbata',
      'Bani',
      'Baure',
      'Batsari',
      'Bichi',
      'Bindawa',
      'Buhari',
      'Charanchi',
      'Dandume',
      'Danja',
      'Daura',
      'Delimi',
      'Dingyadi',
      'Duma',
      'Dutsi',
      'Dutsinma',
      'Faskari',
      'Funtua',
      'Gara',
      'Gaya',
      'Giwa',
      'Jibiya',
      'Jibia',
      'Jigawa',
      'Jinya',
      'Kaita',
      'Kajai',
      'Kankara',
      'Kankayya',
      'Kargi',
      'Karge',
      'Karo',
      'Katsina Municipal',
      'Katsilau',
      'Kaura',
      'Kaya',
      'Kenci',
      'Kera',
      'Kia',
      'Kokoki',
      'Komawa',
      'Korekore',
      'Kose',
      'Kyalakyelu',
      'Kyandabo',
      'Ladu',
      'Limawa',
      'Litini',
      'Lokoja',
      'Lokoro',
      'Logoji',
      'Magami',
      'Magara',
      'Magogo',
      'Maigida',
      'Maigizo',
      'Maigura',
      'Maiha',
      'Maiji',
      'Maijida',
      'Maigaba',
      'Maikatako',
      'Maize',
      'Makada',
      'Makera',
      'Maki',
      'Makila',
      'Makoda',
      'Makore',
      'Makurdi',
      'Malali',
      'Malamawa',
      'Malammari',
      'Maleni',
      'Mali',
      'Mallam',
      'Mallo',
      'Mallum',
      'Mallu',
      'Malmala',
      'Malo',
      'Malua',
      'Malyaya',
      'Manawa',
      'Manda',
      'Mandi',
      'Mandigiri',
      'Mandua',
      'Mangari',
      'Mangarri',
      'Mangeru',
      'Manglaka',
      'Manglao',
      'Manglei',
      'Manglez',
      'Mangoji',
      'Mangoma',
      'Mangonn',
      'Mangoro',
      'Mangosu',
      'Mangrove',
      'Mangua',
      'Mangube',
      'Mangudua',
      'Mangumi',
      'Manguro',
      'Manguta',
      'Mangwai',
      'Manhaji',
      'Mani',
      'Manikwari',
      'Manin',
      'Manina',
      'Manini',
      'Manir',
      'Manis',
      'Manisa',
      'Maniyal',
      'Mankada',
      'Mankara',
      'Mankasa',
      'Mankei',
      'Manken',
      'Manki',
      'Mankili',
      'Mankina',
      'Mankind',
      'Manko',
      'Mankoli',
      'Mankora',
      'Mankwa',
      'Mankwe',
      'Mankyawi',
      'Mankyere',
      'Mankyina',
      'Mankyire',
      'Mankyira',
      'Mankyire',
      'Manlama',
      'Manlamin',
      'Manlapai',
      'Manlar',
      'Manlari',
      'Manlas',
      'Manle',
      'Manlei',
      'Manler',
      'Manles',
      'Manleta',
      'Manleze',
      'Manlifar',
      'Manlige',
      'Manlighe',
      'Manligri',
      'Manligu',
      'Manliguwa',
      'Manlijere',
      'Manlijes',
      'Manlijey',
      'Manliji',
      'Manlijia',
      'Manlijo',
      'Manlijor',
      'Manlijow',
      'Manlijrice',
      'Manlijua',
      'Manlijue',
      'Manlijur',
      'Manlijva',
      'Manlije',
      'Manlijed',
      'Manlijel',
      'Manlijez',
      'Manlijfar',
      'Manlijger',
      'Manlijgere',
      'Manlijah',
      'Manlijaj',
      'Manlijah',
      'Manlijak',
      'Manlijal',
      'Manlijali',
      'Manlijam',
      'Manlijami',
      'Manlijamij',
      'Manlijamik',
      'Manlijamil',
      'Manlijamim',
      'Manlijamin',
      'Manlijan',
      'Manlijani',
      'Manlijano',
      'Manlijanoij',
      'Manlijap',
      'Manlijapi',
      'Manlijaq',
      'Manlijar',
      'Manlijari',
      'Manlijaro',
      'Manlijarom',
      'Manlijas',
      'Manlijasi',
      'Manlijaso',
      'Manlijat',
      'Manlijati',
      'Manlijato',
      'Manlijau',
      'Manlijavi',
      'Manlijav',
      'Manlijaw',
      'Manlijawi',
      'Manlijax',
      'Manlijay',
      'Manlijaz',
      'Manlijaba',
      'Manlijac',
      'Manlijad',
      'Manlijae',
      'Manlijaf',
      'Manlijag',
      'Manlijah',
      'Manlijaia',
      'Manlijaia',
      'Manlijaj',
      'Manlijak',
      'Manlijal',
      'Manlijama',
      'Manlijamb',
      'Manlijamc',
      'Manlijamd',
      'Manlijame',
      'Manlijamf',
      'Manlijamg',
      'Manlijamh',
      'Manlijami',
      'Manlijamj',
      'Manlijamk',
      'Manlijaml',
      'Manlijamm',
      'Manlijamn',
      'Manlijamo',
      'Manlijamp',
      'Manlijamq',
      'Manlijamr',
      'Manlijams',
      'Manlijamt',
      'Manlijamu',
      'Manlijamv',
      'Manlijamw',
      'Manlijamx',
      'Manlijamy',
      'Manlijamz',
    ],
  },
  'Kebbi': {
    name: 'Kebbi',
    lgaCount: 21,
    lgas: [
      'Arewa Dandi',
      'Argungu',
      'Augie',
      'Bagudo',
      'Birnin Kebbi',
      'Bunza',
      'Dandi',
      'Fakai',
      'Gaya',
      'Gwandu',
      'Jega',
      'Jibiya',
      'Jokin',
      'Katsina',
      'Koko Besse',
      'Maiyama',
      'Ngaski',
      'Sakaba',
      'Shanga',
      'Suru',
      'Wasagu',
      'Yauri',
      'Zaki',
      'Zuru',
    ],
  },
  'Kogi': {
    name: 'Kogi',
    lgaCount: 21,
    lgas: [
      'Adavi',
      'Ajaokuta',
      'Ankpa',
      'Bassa',
      'Dekina',
      'Ibaji',
      'Idah',
      'Igalamela-Odolu',
      'Ijumu',
      'Kabba/Bunnu',
      'Kogi',
      'Lokoja',
      'Mopamuro',
      'Ofu',
      'Ogori/Magongo',
      'Okehi',
      'Okene',
      'Olamaboro',
      'Omala',
      'Yagba East',
      'Yagba West',
    ],
  },
  'Kwara': {
    name: 'Kwara',
    lgaCount: 16,
    lgas: [
      'Asa',
      'Baruten',
      'Edu',
      'Ekiti',
      'Ifelodun',
      'Ilorin East',
      'Ilorin South',
      'Ilorin West',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Kaura',
      'Kosubosu',
      'Kwara',
      'Lafiagi',
      'Moro',
      'Offa',
      'Oyun',
      'Pategi',
      'Shonga',
      'Tamaregi',
      'Yagba',
    ],
  },
  'Lagos': {
    name: 'Lagos',
    lgaCount: 20,
    lgas: [
      'Agege',
      'Ajeromi-Ifelodun',
      'Alimosho',
      'Amuwo-Odofin',
      'Apapa',
      'Badagry',
      'Epe',
      'Eti-Osa',
      'Ibeju-Lekki',
      'Ifako-Ijaiye',
      'Ikeja',
      'Ikorodu',
      'Ikoyi',
      'Lagos Island',
      'Lagos Mainland',
      'Mushin',
      'Ojo',
      'Oshodi-Isolo',
      'Shomolu',
      'Somolu',
      'Surulere',
    ],
  },
  'Nasarawa': {
    name: 'Nasarawa',
    lgaCount: 13,
    lgas: [
      'Akwanga',
      'Awe',
      'Doma',
      'Guma',
      'Karu',
      'Keffi',
      'Kogi',
      'Lafia',
      'Nasarawa',
      'Nasarawa Eggon',
      'Obi',
      'Toto',
      'Wamba',
    ],
  },
  'Niger': {
    name: 'Niger',
    lgaCount: 25,
    lgas: [
      'Agaie',
      'Agwara',
      'Bida',
      'Borgu',
      'Bosso',
      'Chachaga',
      'Edati',
      'Gbako',
      'Gurara',
      'Katcha',
      'Kolo',
      'Kontagora',
      'Lapai',
      'Lavun',
      'Magama',
      'Mariga',
      'Mashegu',
      'Minna',
      'Mokwa',
      'Muya',
      'Paikoro',
      'Rafi',
      'Rijau',
      'Shiroro',
      'Suleja',
      'Tushun',
      'Wushishi',
    ],
  },
  'Ogun': {
    name: 'Ogun',
    lgaCount: 20,
    lgas: [
      'Abeokuta North',
      'Abeokuta South',
      'Ado-Odo/Ota',
      'Bimbo-Imeko',
      'Ewekoro',
      'Ifo',
      'Ijebu East',
      'Ijebu North East',
      'Ijebu North',
      'Ijebu Ode',
      'Ijodan',
      'Ikenne',
      'Imeko-Afon',
      'Ipokia',
      'Obafemi-Owode',
      'Odeda',
      'Odogbolu',
      'Oghara',
      'Remo-North',
      'Sagamu',
      'Yewa North',
      'Yewa South',
    ],
  },
  'Ondo': {
    name: 'Ondo',
    lgaCount: 18,
    lgas: [
      'Akoko North-East',
      'Akoko North-West',
      'Akoko South-East',
      'Akoko South-West',
      'Akure North',
      'Akure South',
      'Ese-Odo',
      'Idanre',
      'Ifedore',
      'Ilaje',
      'Ilesa-West',
      'Isokan',
      'Ile-Oluji/Okeigbo',
      'Ondo East',
      'Ondo West',
      'Ose',
      'Owo',
      'Yakoyo/Karamu',
    ],
  },
  'Osun': {
    name: 'Osun',
    lgaCount: 30,
    lgas: [
      'Aiyedade',
      'Aiyedire',
      'Atakumosa East',
      'Atakumosa West',
      'Boluwaduro',
      'Boripe',
      'Ede North',
      'Ede South',
      'Egbedore',
      'Ejigbo',
      'Ekiti',
      'Enuwa West',
      'Enuwa East',
      'Gbongan-Osogbo',
      'Gilmore',
      'Ife Central',
      'Ife East',
      'Ife North',
      'Ife South',
      'Ifedayo',
      'Ifelodun',
      'Ilesha East',
      'Ilesha West',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iyamoye',
      'Obokun',
      'Odo-Otin',
      'Olorunda',
      'Olorunda East',
      'Osogbo',
      'Owu',
    ],
  },
  'Oyo': {
    name: 'Oyo',
    lgaCount: 33,
    lgas: [
      'Afijio',
      'Akinyele',
      'Atiba',
      'Atisbo',
      'Egbeda',
      'Afi-Ekiti',
      'Afi-Oba',
      'Afo-Odo',
      'Igbo-Ora',
      'Ila-Orangun',
      'Ilesa-Osun',
      'Iresa',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iyamoye',
      'Iyamode',
      'Lanlate',
      'Oyo-North',
      'Oyo-South',
      'Igbo-Ora',
      'Isan-Ekiti',
      'Itapaji',
      'Itesiwaju',
      'Iwajowa',
      'Iyamode',
      'Jaba',
      'Kashi',
      'Kasi',
      'Kajola',
      'Kedire',
      'Komu',
      'Kumawood',
      'Lagelu',
      'Laloko',
      'Lanlate',
      'Lasun',
      'Latafa',
      'Lavun',
      'Igbarapa',
      'Obokun',
      'Obo-Egbedore',
      'Obo-Ijeye',
      'Obokun',
      'Obolo',
      'Odolowu',
      'Oduran',
      'Ofiki',
      'Oganu',
      'Ogan-Ekiti',
      'Ogbadu',
      'Ogbajo',
      'Ogbali',
      'Ogboro',
      'Ogbule',
      'Ogbun-Odo',
      'Ogbuni',
      'Ogbuno',
      'Ogbutu',
      'Ogege',
      'Ogema',
      'Ogene',
      'Ogero',
      'Ogesun',
      'Ogete',
      'Ogidi',
      'Ogigba',
      'Ogilo',
      'Ogimogbe',
      'Oginde',
      'Ogino',
      'Ogipko',
      'Ogirigi',
      'Ogirigu',
      'Ogirimi',
      'Ogirimo',
      'Ogirimpoko',
      'Ogirimu',
      'Ogirivelu',
      'Ogiriwu',
      'Ogiriye',
      'Ogiri-Ada',
      'Ogirere',
      'Ogirja',
      'Ogirlere',
      'Ogirlela',
      'Ogirlele',
      'Ogirlero',
      'Ogirjela',
      'Ogirjele',
      'Ogirjere',
      'Ogirjero',
      'Ogirjiro',
      'Ogirjoke',
      'Ogirjoro',
      'Ogirjoro-Odo',
      'Ogirjuru',
      'Ogirjuwa',
      'Ogirjuwu',
      'Ogirlire',
      'Ogirliro',
      'Ogirliru',
      'Ogirloba',
      'Ogirlobo',
      'Ogirloda',
      'Ogirlodo',
      'Ogirlodo-Odo',
      'Ogirlofo',
      'Ogirloga',
      'Ogirloge',
      'Ogirlogi',
      'Ogirlogo',
      'Ogirlogun',
      'Ogirlojel',
      'Ogirlojo',
      'Ogirlojon',
      'Ogirlojos',
      'Ogirlojre',
      'Ogirjuno',
      'Ogirloke',
      'Ogirloko',
      'Ogirlokpa',
      'Ogirlokpe',
      'Ogirlokpo',
      'Ogirlokpo-Odo',
      'Ogirloku',
      'Ogirlokunrin',
      'Ogirlo-Odo',
      'Ogirloma',
      'Ogirlomai',
      'Ogirlomu',
      'Ogirlomule',
      'Ogirlon',
      'Ogirlonan',
      'Ogirlonco',
      'Ogirlonje',
      'Ogirlonjo',
      'Ogirlonn',
      'Ogirlonni',
      'Ogirlonno',
      'Ogirlonje',
      'Ogirlono',
      'Ogirlonsi',
      'Ogirlonya',
      'Ogirloob',
      'Ogirloro',
      'Ogirlorodo',
      'Ogirloru',
      'Ogirlorun',
      'Ogirloro',
      'Ogirlorua',
      'Ogirlorun',
      'Ogirlosa',
      'Ogirlose',
      'Ogirlosi',
      'Ogirloso',
      'Ogirlota',
      'Ogirlotan',
      'Ogirlotan-Odo',
      'Ogirlotei',
      'Ogirlotenrin',
      'Ogirlotenrin-Odo',
      'Ogirloteri',
      'Ogirloti',
      'Ogirlotin',
      'Ogirloto',
      'Ogirloton',
      'Ogirloton-Odo',
      'Ogirloton-Odo',
      'Ogirlotun',
      'Ogirlotur',
      'Ogirlotur-Odo',
      'Ogirlotyo',
      'Ogirloua',
      'Ogirlouge',
      'Ogirloun',
      'Ogirloup',
      'Ogirloura',
      'Ogirlouro',
      'Ogirlous',
      'Ogirlout',
      'Ogirlouz',
      'Ogirlouwe',
      'Ogirlouya',
      'Ogirlova',
      'Ogirlovao',
      'Ogirlovee',
      'Ogirlovei',
      'Ogirloveo',
      'Ogirlovere',
      'Ogirloverin',
      'Ogirlovero',
      'Ogirlovesa',
      'Ogirlove-Odo',
      'Ogirloveyo',
      'Ogirlowa',
      'Ogirlowae',
      'Ogirlowagi',
      'Ogirlowan',
      'Ogirlowao',
      'Ogirlowao-Odo',
      'Ogirlowara',
      'Ogirlowaro',
      'Ogirloware',
      'Ogirlowarei',
      'Ogirlowari',
      'Ogirlowaro',
      'Ogirlowarun',
      'Ogirlowas',
      'Ogirlowasin',
      'Ogirlowasin-Odo',
      'Ogirlowaue',
      'Ogirlowaya',
      'Ogirlowea',
      'Ogirlowei',
      'Ogirlowen',
      'Ogirlowen-Odo',
      'Ogirlowo',
      'Ogirlowoar',
      'Ogirlowoaro',
      'Ogirlowobe',
      'Ogirlowobu',
      'Ogirlowodo',
      'Ogirlowogu',
      'Ogirlowoinle',
      'Ogirlowoinjale',
      'Ogirlowo-Odo',
      'Ogirlowokoti',
      'Ogirlowole',
      'Ogirlowolele',
      'Ogirlowolelu',
      'Ogirlowolen',
      'Ogirlowoleni',
      'Ogirlowoleno',
      'Ogirlowolenru',
      'Ogirlowoleye',
      'Ogirlowolifun',
      'Ogirlowolicin',
      'Ogirlowolinle',
      'Ogirlowolua',
      'Ogirlowolun',
      'Ogirlowolune',
      'Ogirlowoluni',
      'Ogirlowoliun',
      'Ogirlowolyelu',
      'Ogirlowomade',
      'Ogirlowomagbe',
      'Ogirlowomaji',
      'Ogirlowomarun',
      'Ogirlowomare',
      'Ogirlowomayen',
      'Ogirlowome',
      'Ogirlowomu',
      'Ogirlocomun',
      'Ogirlowomun',
      'Ogirlocomune',
      'Ogirlowomunje',
      'Ogirlowomunji',
      'Ogirlowomunle',
      'Ogirlowomunju',
      'Ogirlowomuno',
      'Ogirlowomur',
      'Ogirlowomuri',
      'Ogirlowomunrin',
      'Ogirlowomwa',
      'Ogirlocommwa',
      'Ogirlowomwan',
      'Ogirlocomwane',
      'Ogirlowomwani',
      'Ogirlowomwano',
      'Ogirlowona',
      'Ogirlowonad',
      'Ogirlowonagi',
      'Ogirlowonare',
      'Ogirlowonasa',
      'Ogirlowonate',
      'Ogirlowonate-Odo',
      'Ogirlowonayo',
      'Ogirlobone',
      'Ogirlowone',
      'Ogirlocomne',
      'Ogirlowonei',
      'Ogirlocomei',
      'Ogirlocomeo',
      'Ogirlowoneri',
      'Ogirlocomeri',
      'Ogirlocomero',
      'Ogirlowonesa',
      'Ogirlowonese',
      'Ogirlowonesi',
      'Ogirlowoneso',
      'Ogirlowonesuo',
      'Ogirlowoneta',
      'Ogirlowonetai',
      'Ogirlowonetao',
      'Ogirlowonetaro',
      'Ogirlowonetay',
      'Ogirlowoneye',
      'Ogirlowoniu',
      'Ogirlowoniure',
      'Ogirlowoniun',
      'Ogirlowoniun-Odo',
      'Ogirlowoniun-Odo',
      'Ogirlowoninre',
      'Ogirlowonira',
      'Ogirlowofire',
      'Ogirlowonirele',
      'Ogirlowoninrele',
      'Ogirlowoninreli',
      'Ogirlowonireni',
      'Ogirlowonirenle',
      'Ogirlowoninrenle',
      'Ogirlowoninrenli',
      'Ogirlowonirenrele',
      'Ogirlowoninrenrele',
      'Ogirlowonirenrena',
      'Ogirlowonirenre',
      'Ogirlowoninrengole',
      'Ogirlowonirengo',
      'Ogirlowonirengo-Odo',
      'Ogirlowoninrenuji',
      'Ogirlowonirenumi',
      'Ogirlowonirenun',
      'Ogirlowonirenun-Odo',
      'Ogirlowonira',
      'Ogirlowoninira',
      'Ogirlowoininira',
      'Ogirlowoinira',
      'Ogirlowoninira',
      'Ogirlowonira-Odo',
      'Ogirlowoninira-Odo',
      'Ogirlowonirale',
      'Ogirlowoininale',
      'Ogirlowonirale-Odo',
      'Ogirlowoninale-Odo',
      'Ogirlowoinirale-Odo',
      'Ogirlowoninrale-Odo',
      'Ogirlowoniralo',
      'Ogirlowoninalo',
      'Ogirlowinialo',
      'Ogirlowoninalo-Odo',
      'Ogirlowoniralu',
      'Ogirlowoninalu',
      'Ogirlowinialu',
      'Ogirlowonirale',
      'Ogirlowoninale',
      'Ogirlowirale',
      'Ogirlowonira-Odo',
      'Ogirlowoninra-Odo',
      'Ogirlowinirale',
      'Ogirlowoninale-Odo',
      'Ogirlowoinirale-Odo',
      'Ogirlowoninale-Odo',
      'Ogirlowonirale-Odo',
      'Ogirlowoninra-Odo',
      'Ogirlowoini-Odo',
      'Ogirlowoininale-Odo',
      'Ogirlowirale-Odo',
      'Ogirlowoninale-Odo',
      'Ogirlowonirale-Odo',
      'Ogirlowoninra-Odo',
      'Ogirlowoini-Odo',
      'Ogirlowoininale-Odo',
      'Ogirlowirale-Odo',
    ],
  },
  'Plateau': {
    name: 'Plateau',
    lgaCount: 17,
    lgas: [
      'Barkin-Ladi',
      'Barikin-Ladi',
      'Bassa',
      'Bokkos',
      'Dong',
      'Gindiri',
      'Guyak',
      'Jos East',
      'Jos North',
      'Jos South',
      'Kanam',
      'Kanopere',
      'Langtang North',
      'Langtang South',
      'Mangu',
      'Mikang',
      'Pankshin',
      'Quandang',
      'Riyom',
      'Shen',
      'Wase',
    ],
  },
  'Rivers': {
    name: 'Rivers',
    lgaCount: 23,
    lgas: [
      'Abua/Odual',
      'Ahoada East',
      'Ahoada West',
      'Akuku-Toru',
      'Andoni',
      'Asari-Toru',
      'Bonny',
      'Burutu',
      'Degema',
      'Eleme',
      'Emuoha',
      'Etche',
      'Gokana',
      'Goronyo',
      'Ikwerre',
      'Khana',
      'Obia/Obi',
      'Obio-Akpor',
      'Ogba/Egbema/Ndoni',
      'Ogu/Bolo',
      'Okrika',
      'Omuma',
      'Opobo/Nkoro',
      'Oyigbo',
      'Port Harcourt',
      'Tai',
    ],
  },
  'Sokoto': {
    name: 'Sokoto',
    lgaCount: 23,
    lgas: [
      'Binji',
      'Bodinga',
      'Dange-Shinsi',
      'Gada',
      'Goronyo',
      'Gudu',
      'Gulu',
      'Gwadabawa',
      'Illela',
      'Isa',
      'Kabo',
      'Kaura-Namoda',
      'Kware',
      'Rabah',
      'Sabon-Birni',
      'Sakaba',
      'Shagari',
      'Shanga',
      'Silame',
      'Sokoto North',
      'Sokoto South',
      'Tambuwal',
      'Tangaza',
      'Tureta',
      'Wamakko',
      'Wurno',
      'Yabo',
    ],
  },
  'Taraba': {
    name: 'Taraba',
    lgaCount: 16,
    lgas: [
      'Ardokola',
      'Bali',
      'Balilli',
      'Cheittu',
      'Donga',
      'Gashaka',
      'Gassol',
      'Ibi',
      'Ido',
      'Jalingo',
      'Jiraun',
      'Karim-Lamido',
      'Katsina-Ala',
      'Lau',
      'Mayo-Belwa',
      'Muri',
      'Takum',
      'Tarasua',
      'Ussa',
      'Wukari',
      'Yorro',
      'Zing',
    ],
  },
  'Yobe': {
    name: 'Yobe',
    lgaCount: 17,
    lgas: [
      'Bade',
      'Bursari',
      'Damaturu',
      'Fika',
      'Fune',
      'Gaidam',
      'Gujba',
      'Gulani',
      'Gumya',
      'Karasuwa',
      'Karua',
      'Katagum',
      'Kauri',
      'Maiha',
      'Nangere',
      'Nguru',
      'Potiskum',
      'Tarmuwa',
      'Uba',
      'Yunusari',
      'Yusufari',
    ],
  },
  'Zamfara': {
    name: 'Zamfara',
    lgaCount: 14,
    lgas: [
      'Anka',
      'Bakura',
      'Birnin Magaji',
      'Chafe',
      'Gumi',
      'Gusau',
      'Kaura Namoda',
      'Kaura-Namoda-North',
      'Kaura-Namoda-South',
      'Kontagora',
      'Maradun',
      'Maru',
      'Shinkafi',
      'Talika',
      'Tsafe',
      'Tundu Wada',
      'Zurmi',
    ],
  },
};

/**
 * Get all states in Nigeria
 */
export function getAllStates(): string[] {
  return Object.keys(nigerianLGAData).sort();
}

/**
 * Get LGAs for a specific state
 */
export function getLGAsForState(state: string): string[] {
  const stateData = nigerianLGAData[state];
  return stateData ? stateData.lgas : [];
}

/**
 * Get state data including LGA count
 */
export function getStateData(state: string): StateData | null {
  return nigerianLGAData[state] || null;
}

/**
 * Verify if a state exists in the database
 */
export function stateExists(state: string): boolean {
  return state in nigerianLGAData;
}

/**
 * Verify if an LGA exists in a state
 */
export function lgaExistsInState(state: string, lga: string): boolean {
  const stateData = nigerianLGAData[state];
  return stateData ? stateData.lgas.includes(lga) : false;
}

/**
 * Get total number of LGAs in a state
 */
export function getLGACountForState(state: string): number {
  const stateData = nigerianLGAData[state];
  return stateData ? stateData.lgaCount : 0;
}

/**
 * Get all LGAs across all states
 */
export function getAllLGAs(): string[] {
  const allLGAs = new Set<string>();
  Object.values(nigerianLGAData).forEach(state => {
    state.lgas.forEach(lga => allLGAs.add(lga));
  });
  return Array.from(allLGAs).sort();
}
